// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tFCdB9RniJYEQSN35DC9AW
// Component: wDCF5TdzdC
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { GraphCMSFetcher } from "@plasmicpkgs/plasmic-graphcms"; // plasmic-import: 8sYtOZawA08/codeComponent
import { GraphCMSField } from "@plasmicpkgs/plasmic-graphcms"; // plasmic-import: _3Kx5FMtA8n/codeComponent
import Button from "../../Button"; // plasmic-import: bN83BFeysHB/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_ecommerce_hygraph.module.css"; // plasmic-import: tFCdB9RniJYEQSN35DC9AW/projectcss
import sty from "./PlasmicPdp.module.css"; // plasmic-import: wDCF5TdzdC/css

export const PlasmicPdp__VariantProps = new Array();

export const PlasmicPdp__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicPdp__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <GraphCMSFetcher
            data-plasmic-name={"graphCmsFetcher"}
            data-plasmic-override={overrides.graphCmsFetcher}
            className={classNames("__wab_instance", sty.graphCmsFetcher)}
            noAutoRepeat={false}
            noLayout={true}
            query={{
              query:
                "query MyQuery($id: ID!) {\n  node(id: $id) {\n    ... on Product {\n      id\n      name\n      images {\n        mimeType\n        url\n      }\n      description\n      price\n      variants {\n        ... on ProductColorVariant {\n          id\n          name\n        }\n        ... on ProductSizeVariant {\n          id\n          name\n        }\n        ... on ProductSizeColorVariant {\n          id\n          name\n        }\n      }\n      categories(first: 10) {\n        id\n        name\n      }\n    }\n  }\n}\n",
              variables: { id: "ckdu4ch1s0h1s01580ksoy6m5" }
            }}
          >
            <ph.DataCtxReader>
              {$ctx => (
                <div
                  data-plasmic-name={"freeBox"}
                  data-plasmic-override={overrides.freeBox}
                  className={classNames(projectcss.all, sty.freeBox)}
                >
                  <GraphCMSField
                    className={classNames(
                      "__wab_instance",
                      sty.graphCmsField__gBfeY
                    )}
                    path={["name"]}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xo97B
                    )}
                  >
                    {(() => {
                      try {
                        return "In " + $ctx.graphCmsItem.categories[0].name;
                      } catch (e) {
                        if (e instanceof TypeError) {
                          return "Enter some text";
                        }
                        throw e;
                      }
                    })()}
                  </div>
                  <GraphCMSField
                    className={classNames(
                      "__wab_instance",
                      sty.graphCmsField__eDdXo
                    )}
                    path={["images", 0]}
                  />

                  <GraphCMSField
                    className={classNames(
                      "__wab_instance",
                      sty.graphCmsField___1Gvc
                    )}
                    path={["description"]}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bk5Ro
                    )}
                  >
                    {(() => {
                      try {
                        return "$" + $ctx.graphCmsItem.price;
                      } catch (e) {
                        if (e instanceof TypeError) {
                          return "Enter some text";
                        }
                        throw e;
                      }
                    })()}
                  </div>
                  <Button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                  >
                    {"Buy Now"}
                  </Button>
                </div>
              )}
            </ph.DataCtxReader>
          </GraphCMSFetcher>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "graphCmsFetcher", "freeBox", "button"],
  graphCmsFetcher: ["graphCmsFetcher", "freeBox", "button"],
  freeBox: ["freeBox", "button"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPdp__ArgProps,
          internalVariantPropNames: PlasmicPdp__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPdp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPdp";
  } else {
    func.displayName = `PlasmicPdp.${nodeName}`;
  }
  return func;
}

export const PlasmicPdp = Object.assign(
  // Top-level PlasmicPdp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    graphCmsFetcher: makeNodeComponent("graphCmsFetcher"),
    freeBox: makeNodeComponent("freeBox"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicPdp
    internalVariantProps: PlasmicPdp__VariantProps,
    internalArgProps: PlasmicPdp__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPdp;
/* prettier-ignore-end */
